// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: calculator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdditionServiceClient is the client API for AdditionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdditionServiceClient interface {
	AddTwoNumbers(ctx context.Context, in *AddTwoNumbRequest, opts ...grpc.CallOption) (*AdditionResponse, error)
}

type additionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdditionServiceClient(cc grpc.ClientConnInterface) AdditionServiceClient {
	return &additionServiceClient{cc}
}

func (c *additionServiceClient) AddTwoNumbers(ctx context.Context, in *AddTwoNumbRequest, opts ...grpc.CallOption) (*AdditionResponse, error) {
	out := new(AdditionResponse)
	err := c.cc.Invoke(ctx, "/calculator.AdditionService/AddTwoNumbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdditionServiceServer is the server API for AdditionService service.
// All implementations must embed UnimplementedAdditionServiceServer
// for forward compatibility
type AdditionServiceServer interface {
	AddTwoNumbers(context.Context, *AddTwoNumbRequest) (*AdditionResponse, error)
	mustEmbedUnimplementedAdditionServiceServer()
}

// UnimplementedAdditionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdditionServiceServer struct {
}

func (UnimplementedAdditionServiceServer) AddTwoNumbers(context.Context, *AddTwoNumbRequest) (*AdditionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTwoNumbers not implemented")
}
func (UnimplementedAdditionServiceServer) mustEmbedUnimplementedAdditionServiceServer() {}

// UnsafeAdditionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdditionServiceServer will
// result in compilation errors.
type UnsafeAdditionServiceServer interface {
	mustEmbedUnimplementedAdditionServiceServer()
}

func RegisterAdditionServiceServer(s grpc.ServiceRegistrar, srv AdditionServiceServer) {
	s.RegisterService(&AdditionService_ServiceDesc, srv)
}

func _AdditionService_AddTwoNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTwoNumbRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdditionServiceServer).AddTwoNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.AdditionService/AddTwoNumbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdditionServiceServer).AddTwoNumbers(ctx, req.(*AddTwoNumbRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdditionService_ServiceDesc is the grpc.ServiceDesc for AdditionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdditionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.AdditionService",
	HandlerType: (*AdditionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTwoNumbers",
			Handler:    _AdditionService_AddTwoNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculator.proto",
}
